### ISSUE TITLE
Update stable version in repo from 0.0.1 to 0.0.3

### ISSUE THREAD

**Issue by GermanBluefox** [TA2k/ioBroker.bestway#1]
# Think about update stable version to 0.0.3
**Version**: stable=**0.0.1** (242 days old) => latest=**0.0.3** (15 days old)
**Installs**: stable=**19** (73.08%), latest=**7** (26.92%), total=**26**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L140)

**Comment by mcm1957** [comment]
This issue seems to be outdated

This issue suggests to update the stable version of this adapter to ${issue.to} but the current stable version is already ${stable[adapter].version}.

So this issue should be closed.

**Comment by mcm1957** [comment]
This issue seems to be outdated

This issue suggests to update the stable version of this adapter to 0.0.3 but the current stable version is already 0.0.4.

So this issue should be closed.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated

This issue suggests to update the stable version of this adapter to 0.0.3 but the current stable version is already 0.0.4.

So this issue should be closed.
