### ISSUE TITLE
Hydro Jet Pro Unit (SanFrancisco) 

### ISSUE THREAD

**Issue by crwblade87** [TA2k/ioBroker.bestway#2]
Hello, Is it possible to add support for Hydro Jet Pro Unit (SanFrancisco) there is now no object yet for HydroJet ? Many thanks

**Comment by TA2k** [comment]
if the device is in the smart hub app is should appear in the adapter

**Comment by crwblade87** [comment]
Yes the Pool is in the Adapter, but there is no object to Control the hydro jets, only the waves are available.

**Comment by TA2k** [comment]
I need an account to check what the app is sending
tombox2020@gmail.com

**Comment by TA2k** [comment]
Please try the github version and the remotev2 folder to control

**Comment by crwblade87** [comment]
I tried it, unfortunately without success Jet = 1. I also noticed that the functions of the v1 don't work either, filters for example. Herr does only „Power“ work. Possibly because it is a new pump model? My old pump still works with the adapter.

**Comment by crwblade87** [comment]
Many thanks, now it works fine
